### PR TITLE
Add documentation for 0.9.14.

### PR DESCRIPTION
**Pull request by mike-jumper**

### CODE REVIEW

**Comment by mike-jumper** [comment]
Yep, it's all automatically generated. The only non-automatic changes would be the release notes, which I separated into their own PR for that reason (#54).

The best way to review the docs within this PR would probably be to just deploy the site locally and see whether the various things under `/doc/0.9.14/` look sane.

**Comment by necouchman** [comment]
Okay, will try to get to this tomorrow - should be able to generate/deploy it and verify pretty quickly.

**Comment by mike-jumper** [comment]
Great! Assuming things go well, I'll then be able to start the vote thread for RC1.

**Comment by necouchman** [comment]
Well, took a little work to Jekyll installed on my system, but I think I got past that.  Now getting this error during build:

    Liquid Exception: Liquid syntax error (line 98): Tag '{%- for release in releases reversed -%}' was not properly terminated with regexp: /\%\}/ in doap.rdf

Did I miss something in reviewing one of the previous changes?  Or is my version of Jekyll too old (3.4.4)?

**Comment by mike-jumper** [comment]
Yep - your Jekyll is too old. That syntax deals with controlling the rendering of whitespace and is relatively new, added in Jekyll 3.5.0:

https://stackoverflow.com/questions/40451313/white-space-control-in-jekyll-why-does-a-la-liquid-not-work

**Comment by necouchman** [comment]
Hmmmm....okay...let me see what I can figure out.  I'm doing most of my Guacamole development on CentOS7, and this means updating Ruby.  Don't really like having to do major updates to package revisions like this, so have to figure out something else.

**Comment by necouchman** [comment]
Okay, got it.  Looks good, will merge shortly.

**Comment by mike-jumper** [comment]
Thanks!

**Pull request merged**
