### PR TITLE
Create GuacamoleBox.md

### PR DESCRIPTION
**Pull request by turtle89431**

### CODE REVIEW

**Comment by necouchman** [comment]
@turtle89431: While we allow for companies that provide commercial support for Guacamole to add their names to our web page, we do not generally allow for the advertisement of other "related" products/services. The changes you're proposing seem to be more of the later and less of the former.

I'll let @mike-jumper overrule me if he thinks it appropriate, but my feeling is that this is a new precedent, and not necessarily some place we want to go.

**Comment by turtle89431** [comment]
we do both commercial support and are providing this superset, we will also be releasing videos on our YouTube page that will be from the basic setup of a guacamole install to adding extensions.

**Comment by necouchman** [comment]
@turtle89431 Understood - however, if you read the descriptions for the other companies, you'll see that the language on them is neutral - even the Keeper company, which does mention one of its products, does not advertise features of the product. Personally, I think the information you provide needs to be 1) more focused on the company, not the product, and 2) more neutral, stating factually what the company does in the way of Guacamole support. The goal is not to cross-advertise Guacamole-like products on this page; the goal is to provide users of Guacamole information on companies that can potentially support their deployments.

**Comment by mike-jumper** [comment]
Yep - we can't list this as-is. I see two main blocking issues with the proposed addition to the list:

1. It includes "Guacamole" in the name of the product, which is against ASF trademark policy: https://www.apache.org/foundation/marks/#products
2. It states that the product is "built upon the original codebase that became Guacamole", which is false and implies a historical origin that is not factual. Guacamole originally started as my personal project, and I can tell you that there is no such original codebase - it _is_ the original codebase. That codebase is and has always been "Guacamole", even before Apache. It did not originate as this third-party product.

@turtle89431:
* You should rename your product such that it does not contain the word "Guacamole", but instead describes itself as "powered by Apache Guacamole".
* You should not state that your product is "built upon the original codebase that became Guacamole", which cannot be correct. You should state that your product is "powered by Apache Guacamole".
* If you do indeed have support for 60 FPS video streaming, you should consider contributing that support for the benefit of the community.

**Pull request closed without merging**
